/*******************************************************************************
	Generated by: DLL to C version 3.91
	Date: 2022-11-6
	Description: The implementation code for rawetrip.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#include "stdafx.h"
#include "Rawetrip.h"


HMODULE g_hRawetrip;
BOOL (WINAPI *Rawetrip_DllEntryPoint)(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved);

extern UCHAR Rawetrip_text[0x27A000];
extern stRawetrip_rdata Rawetrip_rdata;
extern stRawetrip_data Rawetrip_data;
extern UCHAR Rawetrip_rsrc[0x1000];
extern UCHAR Rawetrip_reloc[0x1D000];

__declspec(align(16)) stRawetrip Rawetrip;

void* __stdcall Rawetrip_RVA(DWORD rvaAddr)
{
	if(rvaAddr==0)
		return g_hRawetrip;
	if(rvaAddr >= 0 && rvaAddr < 0x769000)
		return (UCHAR*)&Rawetrip + rvaAddr;

	return NULL;
}

BOOL Rawetrip_Init()
{
	HMODULE hDll;
	DWORD oldProtect;
	void (*fInitData)(HMODULE,void*,void*);

	oldProtect = PAGE_EXECUTE_READWRITE;
	VirtualProtect(&Rawetrip,sizeof(Rawetrip),PAGE_EXECUTE_READWRITE,&oldProtect);

	memcpy(&Rawetrip.Text,&Rawetrip_text,sizeof(Rawetrip_text));
	memcpy(&Rawetrip.Rdata,&Rawetrip_rdata,sizeof(Rawetrip_rdata));
	memcpy(&Rawetrip.Data,&Rawetrip_data,sizeof(Rawetrip_data));
	memcpy(&Rawetrip.Rsrc,&Rawetrip_rsrc,sizeof(Rawetrip_rsrc));
	memcpy(&Rawetrip.Reloc,&Rawetrip_reloc,sizeof(Rawetrip_reloc));

	hDll = ::LoadLibraryA("CRYPT32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"CRYPT32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B030) = ::GetProcAddress(hDll,"CertCreateCertificateChainEngine");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B030))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B034) = ::GetProcAddress(hDll,"CryptQueryObject");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B034))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B038) = ::GetProcAddress(hDll,"CertGetCertificateChain");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B038))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B03C) = ::GetProcAddress(hDll,"CertFreeCertificateChain");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B03C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B040) = ::GetProcAddress(hDll,"CertGetNameStringA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B040))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B044) = ::GetProcAddress(hDll,"CertFindExtension");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B044))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B048) = ::GetProcAddress(hDll,"CertAddCertificateContextToStore");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B048))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B04C) = ::GetProcAddress(hDll,"CryptDecodeObjectEx");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B04C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B050) = ::GetProcAddress(hDll,"PFXImportCertStore");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B050))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B054) = ::GetProcAddress(hDll,"CryptStringToBinaryA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B054))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B058) = ::GetProcAddress(hDll,"CertFreeCertificateContext");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B058))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B05C) = ::GetProcAddress(hDll,"CertFindCertificateInStore");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B05C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B060) = ::GetProcAddress(hDll,"CertEnumCertificatesInStore");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B060))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B064) = ::GetProcAddress(hDll,"CertCloseStore");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B064))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B068) = ::GetProcAddress(hDll,"CertFreeCertificateChainEngine");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B068))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B06C) = ::GetProcAddress(hDll,"CertOpenStore");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B06C))
		return FALSE;

	hDll = ::LoadLibraryA("WLDAP32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"WLDAP32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B460) = ::GetProcAddress(hDll,(LPCSTR)0x32);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B460))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B464) = ::GetProcAddress(hDll,(LPCSTR)0x29);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B464))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B468) = ::GetProcAddress(hDll,(LPCSTR)0x2D);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B468))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B46C) = ::GetProcAddress(hDll,(LPCSTR)0x1B);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B46C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B470) = ::GetProcAddress(hDll,(LPCSTR)0x16);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B470))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B474) = ::GetProcAddress(hDll,(LPCSTR)0xD3);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B474))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B478) = ::GetProcAddress(hDll,(LPCSTR)0x20);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B478))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B47C) = ::GetProcAddress(hDll,(LPCSTR)0x21);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B47C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B480) = ::GetProcAddress(hDll,(LPCSTR)0x23);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B480))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B484) = ::GetProcAddress(hDll,(LPCSTR)0x4F);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B484))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B488) = ::GetProcAddress(hDll,(LPCSTR)0x1E);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B488))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B48C) = ::GetProcAddress(hDll,(LPCSTR)0xC8);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B48C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B490) = ::GetProcAddress(hDll,(LPCSTR)0x2E);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B490))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B494) = ::GetProcAddress(hDll,(LPCSTR)0x12D);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B494))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B498) = ::GetProcAddress(hDll,(LPCSTR)0x3C);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B498))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B49C) = ::GetProcAddress(hDll,(LPCSTR)0xD9);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B49C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4A0) = ::GetProcAddress(hDll,(LPCSTR)0x8F);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4A0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4A4) = ::GetProcAddress(hDll,(LPCSTR)0x1A);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4A4))
		return FALSE;

	hDll = ::LoadLibraryA("Normaliz.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"Normaliz.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B398) = ::GetProcAddress(hDll,"IdnToAscii");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B398))
		return FALSE;

	hDll = ::LoadLibraryA("KERNEL32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"KERNEL32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B084) = ::GetProcAddress(hDll,"GlobalAlloc");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B084))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B088) = ::GetProcAddress(hDll,"CreateDirectoryA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B088))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B08C) = ::GetProcAddress(hDll,"VirtualProtect");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B08C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B090) = ::GetProcAddress(hDll,"GetTickCount");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B090))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B094) = ::GetProcAddress(hDll,"WideCharToMultiByte");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B094))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B098) = ::GetProcAddress(hDll,"FindFirstFileA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B098))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B09C) = ::GetProcAddress(hDll,"FindNextFileA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B09C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0A0) = ::GetProcAddress(hDll,"FindClose");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0A0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0A4) = ::GetProcAddress(hDll,"GetWindowsDirectoryA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0A4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0A8) = ::GetProcAddress(hDll,"MultiByteToWideChar");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0A8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0AC) = ::GetProcAddress(hDll,"GlobalFree");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0AC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0B0) = ::GetProcAddress(hDll,"GlobalLock");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0B0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0B4) = ::GetProcAddress(hDll,"GlobalUnlock");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0B4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0B8) = ::GetProcAddress(hDll,"LoadLibraryA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0B8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0BC) = ::GetProcAddress(hDll,"QueryPerformanceFrequency");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0BC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0C0) = ::GetProcAddress(hDll,"GetProcAddress");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0C0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0C4) = ::GetProcAddress(hDll,"VerSetConditionMask");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0C4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0C8) = ::GetProcAddress(hDll,"VerifyVersionInfoW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0C8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0CC) = ::GetProcAddress(hDll,"QueryPerformanceCounter");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0CC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0D0) = ::GetProcAddress(hDll,"WriteProcessMemory");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0D0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0D4) = ::GetProcAddress(hDll,"SetConsoleTextAttribute");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0D4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0D8) = ::GetProcAddress(hDll,"SetConsoleTitleA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0D8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0DC) = ::GetProcAddress(hDll,"GetCurrentProcess");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0DC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0E0) = ::GetProcAddress(hDll,"GetStdHandle");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0E0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0E4) = ::GetProcAddress(hDll,"GetModuleHandleA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0E4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0E8) = ::GetProcAddress(hDll,"FreeConsole");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0E8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0EC) = ::GetProcAddress(hDll,"CreateThread");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0EC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0F0) = ::GetProcAddress(hDll,"Beep");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0F0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0F4) = ::GetProcAddress(hDll,"AllocConsole");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0F4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0F8) = ::GetProcAddress(hDll,"FindNextFileW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0F8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B0FC) = ::GetProcAddress(hDll,"EnterCriticalSection");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B0FC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B100) = ::GetProcAddress(hDll,"Sleep");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B100))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B104) = ::GetProcAddress(hDll,"LeaveCriticalSection");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B104))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B108) = ::GetProcAddress(hDll,"DeleteCriticalSection");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B108))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B10C) = ::GetProcAddress(hDll,"GetLastError");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B10C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B110) = ::GetProcAddress(hDll,"SleepEx");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B110))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B114) = ::GetProcAddress(hDll,"GetSystemDirectoryA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B114))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B118) = ::GetProcAddress(hDll,"FreeLibrary");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B118))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B11C) = ::GetProcAddress(hDll,"SetLastError");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B11C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B120) = ::GetProcAddress(hDll,"FormatMessageW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B120))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B124) = ::GetProcAddress(hDll,"MoveFileExA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B124))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B128) = ::GetProcAddress(hDll,"CloseHandle");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B128))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B12C) = ::GetProcAddress(hDll,"WaitForSingleObjectEx");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B12C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B130) = ::GetProcAddress(hDll,"GetEnvironmentVariableA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B130))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B134) = ::GetProcAddress(hDll,"GetFileType");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B134))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B138) = ::GetProcAddress(hDll,"ReadFile");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B138))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B13C) = ::GetProcAddress(hDll,"PeekNamedPipe");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B13C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B140) = ::GetProcAddress(hDll,"WaitForMultipleObjects");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B140))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B144) = ::GetProcAddress(hDll,"CreateFileA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B144))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B148) = ::GetProcAddress(hDll,"GetFileSizeEx");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B148))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B14C) = ::GetProcAddress(hDll,"AreFileApisANSI");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B14C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B150) = ::GetProcAddress(hDll,"GetFileInformationByHandleEx");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B150))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B154) = ::GetProcAddress(hDll,"InitializeCriticalSectionAndSpinCount");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B154))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B158) = ::GetProcAddress(hDll,"SetEvent");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B158))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B15C) = ::GetProcAddress(hDll,"ResetEvent");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B15C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B160) = ::GetProcAddress(hDll,"CreateEventW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B160))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B164) = ::GetProcAddress(hDll,"GetModuleHandleW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B164))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B168) = ::GetProcAddress(hDll,"UnhandledExceptionFilter");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B168))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B16C) = ::GetProcAddress(hDll,"SetUnhandledExceptionFilter");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B16C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B170) = ::GetProcAddress(hDll,"TerminateProcess");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B170))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B174) = ::GetProcAddress(hDll,"IsProcessorFeaturePresent");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B174))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B178) = ::GetProcAddress(hDll,"IsDebuggerPresent");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B178))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B17C) = ::GetProcAddress(hDll,"GetCurrentProcessId");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B17C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B180) = ::GetProcAddress(hDll,"GetCurrentThreadId");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B180))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B184) = ::GetProcAddress(hDll,"GetFileAttributesExW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B184))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B188) = ::GetProcAddress(hDll,"GetSystemTimeAsFileTime");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B188))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B18C) = ::GetProcAddress(hDll,"InitializeSListHead");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B18C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B190) = ::GetProcAddress(hDll,"InitializeCriticalSectionEx");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B190))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B194) = ::GetProcAddress(hDll,"FindFirstFileExW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B194))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B198) = ::GetProcAddress(hDll,"CreateFileW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B198))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B19C) = ::GetProcAddress(hDll,"CreateDirectoryW");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B19C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1A0) = ::GetProcAddress(hDll,"LocalFree");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1A0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1A4) = ::GetProcAddress(hDll,"FormatMessageA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1A4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1A8) = ::GetProcAddress(hDll,"LoadLibraryExA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1A8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1AC) = ::GetProcAddress(hDll,"GetModuleFileNameA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1AC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1B0) = ::GetProcAddress(hDll,"FlushInstructionCache");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1B0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1B4) = ::GetProcAddress(hDll,"K32GetModuleInformation");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1B4))
		return FALSE;

	hDll = ::LoadLibraryA("USER32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"USER32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B3AC) = ::GetProcAddress(hDll,"ClientToScreen");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3AC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3B0) = ::GetProcAddress(hDll,"GetKeyState");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3B0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3B4) = ::GetProcAddress(hDll,"SetClipboardData");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3B4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3B8) = ::GetProcAddress(hDll,"EmptyClipboard");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3B8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3BC) = ::GetProcAddress(hDll,"LoadCursorA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3BC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3C0) = ::GetProcAddress(hDll,"ScreenToClient");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3C0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3C4) = ::GetProcAddress(hDll,"CloseClipboard");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3C4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3C8) = ::GetProcAddress(hDll,"OpenClipboard");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3C8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3CC) = ::GetProcAddress(hDll,"GetAsyncKeyState");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3CC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3D0) = ::GetProcAddress(hDll,"CallWindowProcA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3D0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3D4) = ::GetProcAddress(hDll,"GetClipboardData");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3D4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3D8) = ::GetProcAddress(hDll,"ReleaseCapture");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3D8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3DC) = ::GetProcAddress(hDll,"SetCapture");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3DC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3E0) = ::GetProcAddress(hDll,"GetCapture");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3E0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3E4) = ::GetProcAddress(hDll,"GetCursorPos");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3E4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3E8) = ::GetProcAddress(hDll,"SetCursorPos");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3E8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3EC) = ::GetProcAddress(hDll,"GetClientRect");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3EC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3F0) = ::GetProcAddress(hDll,"SetCursor");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3F0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3F4) = ::GetProcAddress(hDll,"GetForegroundWindow");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3F4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3F8) = ::GetProcAddress(hDll,"IsChild");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3F8))
		return FALSE;

	hDll = ::LoadLibraryA("ADVAPI32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"ADVAPI32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B000) = ::GetProcAddress(hDll,"GetUserNameA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B000))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B004) = ::GetProcAddress(hDll,"CryptAcquireContextA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B004))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B008) = ::GetProcAddress(hDll,"CryptReleaseContext");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B008))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B00C) = ::GetProcAddress(hDll,"CryptGetHashParam");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B00C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B010) = ::GetProcAddress(hDll,"CryptGenRandom");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B010))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B014) = ::GetProcAddress(hDll,"CryptCreateHash");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B014))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B018) = ::GetProcAddress(hDll,"CryptHashData");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B018))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B01C) = ::GetProcAddress(hDll,"CryptDestroyHash");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B01C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B020) = ::GetProcAddress(hDll,"CryptDestroyKey");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B020))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B024) = ::GetProcAddress(hDll,"CryptImportKey");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B024))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B028) = ::GetProcAddress(hDll,"CryptEncrypt");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B028))
		return FALSE;

	hDll = ::LoadLibraryA("SHELL32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"SHELL32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B3A0) = ::GetProcAddress(hDll,"ShellExecuteA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3A0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B3A4) = ::GetProcAddress(hDll,"SHGetFolderPathA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B3A4))
		return FALSE;

	hDll = ::LoadLibraryA("MSVCP140.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"MSVCP140.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B1BC) = ::GetProcAddress(hDll,"_Query_perf_counter");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1BC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1C0) = ::GetProcAddress(hDll,"_Thrd_sleep");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1C0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1C4) = ::GetProcAddress(hDll,"?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1C4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1C8) = ::GetProcAddress(hDll,"?_Xbad_alloc@std@@YAXXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1C8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1CC) = ::GetProcAddress(hDll,"?_Xlength_error@std@@YAXPBD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1CC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1D0) = ::GetProcAddress(hDll,"?_Xout_of_range@std@@YAXPBD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1D0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1D4) = ::GetProcAddress(hDll,"??1_Lockit@std@@QAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1D4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1D8) = ::GetProcAddress(hDll,"??0_Lockit@std@@QAE@H@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1D8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1DC) = ::GetProcAddress(hDll,"?_Getgloballocale@locale@std@@CAPAV_Locimp@12@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1DC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1E0) = ::GetProcAddress(hDll,"?uncaught_exception@std@@YA_NXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1E0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1E4) = ::GetProcAddress(hDll,"?id@?$codecvt@DDU_Mbstatet@@@std@@2V0locale@2@A");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1E4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1E8) = ::GetProcAddress(hDll,"?_Fiopen@std@@YAPAU_iobuf@@PBDHH@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1E8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1EC) = ::GetProcAddress(hDll,"?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAE_JPBD_J@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1EC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1F0) = ::GetProcAddress(hDll,"?fill@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1F0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1F4) = ::GetProcAddress(hDll,"?tie@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEPAV?$basic_ostream@DU?$char_traits@D@std@@@2@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1F4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1F8) = ::GetProcAddress(hDll,"?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEXXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1F8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B1FC) = ::GetProcAddress(hDll,"?_Getcat@?$codecvt@DDU_Mbstatet@@@std@@SAIPAPBVfacet@locale@2@PBV42@@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B1FC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B200) = ::GetProcAddress(hDll,"?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@D@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B200))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B204) = ::GetProcAddress(hDll,"?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B204))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B208) = ::GetProcAddress(hDll,"?getloc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QBE?AVlocale@2@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B208))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B20C) = ::GetProcAddress(hDll,"?sbumpc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B20C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B210) = ::GetProcAddress(hDll,"?sgetc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B210))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B214) = ::GetProcAddress(hDll,"?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B214))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B218) = ::GetProcAddress(hDll,"?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B218))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B21C) = ::GetProcAddress(hDll,"?unshift@?$codecvt@DDU_Mbstatet@@@std@@QBEHAAU_Mbstatet@@PAD1AAPAD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B21C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B220) = ::GetProcAddress(hDll,"??0?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B220))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B224) = ::GetProcAddress(hDll,"?setg@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEXPAD00@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B224))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B228) = ::GetProcAddress(hDll,"?_Init@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEXXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B228))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B22C) = ::GetProcAddress(hDll,"?_Init@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEXPAPAD0PAH001@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B22C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B230) = ::GetProcAddress(hDll,"?clear@?$basic_ios@DU?$char_traits@D@std@@@std@@QAEXH_N@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B230))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B234) = ::GetProcAddress(hDll,"??0?$basic_istream@DU?$char_traits@D@std@@@std@@QAE@PAV?$basic_streambuf@DU?$char_traits@D@std@@@1@_N@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B234))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B238) = ::GetProcAddress(hDll,"?in@?$codecvt@DDU_Mbstatet@@@std@@QBEHAAU_Mbstatet@@PBD1AAPBDPAD3AAPAD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B238))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B23C) = ::GetProcAddress(hDll,"?out@?$codecvt@DDU_Mbstatet@@@std@@QBEHAAU_Mbstatet@@PBD1AAPBDPAD3AAPAD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B23C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B240) = ::GetProcAddress(hDll,"?eback@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IBEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B240))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B244) = ::GetProcAddress(hDll,"?gptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IBEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B244))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B248) = ::GetProcAddress(hDll,"?pptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IBEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B248))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B24C) = ::GetProcAddress(hDll,"?egptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IBEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B24C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B250) = ::GetProcAddress(hDll,"?gbump@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEXH@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B250))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B254) = ::GetProcAddress(hDll,"?epptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IBEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B254))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B258) = ::GetProcAddress(hDll,"?_Gndec@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B258))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B25C) = ::GetProcAddress(hDll,"?_Gninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B25C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B260) = ::GetProcAddress(hDll,"?_Gnavail@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IBE_JXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B260))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B264) = ::GetProcAddress(hDll,"?pbump@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEXH@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B264))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B268) = ::GetProcAddress(hDll,"?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B268))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B26C) = ::GetProcAddress(hDll,"?_Pnavail@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IBE_JXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B26C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B270) = ::GetProcAddress(hDll,"?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QAEXH_N@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B270))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B274) = ::GetProcAddress(hDll,"?rdbuf@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEPAV?$basic_streambuf@DU?$char_traits@D@std@@@2@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B274))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B278) = ::GetProcAddress(hDll,"??0?$basic_ios@DU?$char_traits@D@std@@@std@@IAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B278))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B27C) = ::GetProcAddress(hDll,"??0?$basic_ostream@DU?$char_traits@D@std@@@std@@QAE@PAV?$basic_streambuf@DU?$char_traits@D@std@@@1@_N@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B27C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B280) = ::GetProcAddress(hDll,"??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B280))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B284) = ::GetProcAddress(hDll,"?showmanyc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MAE_JXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B284))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B288) = ::GetProcAddress(hDll,"?xsgetn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MAE_JPAD_J@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B288))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B28C) = ::GetProcAddress(hDll,"?xsputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MAE_JPBD_J@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B28C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B290) = ::GetProcAddress(hDll,"??1?$basic_ios@DU?$char_traits@D@std@@@std@@UAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B290))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B294) = ::GetProcAddress(hDll,"??1?$basic_ostream@DU?$char_traits@D@std@@@std@@UAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B294))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B298) = ::GetProcAddress(hDll,"??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B298))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B29C) = ::GetProcAddress(hDll,"??1?$basic_istream@DU?$char_traits@D@std@@@std@@UAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B29C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2A0) = ::GetProcAddress(hDll,"?width@ios_base@std@@QAE_J_J@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2A0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2A4) = ::GetProcAddress(hDll,"?width@ios_base@std@@QBE_JXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2A4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2A8) = ::GetProcAddress(hDll,"?flags@ios_base@std@@QBEHXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2A8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2AC) = ::GetProcAddress(hDll,"?good@ios_base@std@@QBE_NXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2AC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2B0) = ::GetProcAddress(hDll,"?always_noconv@codecvt_base@std@@QBE_NXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2B0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2B4) = ::GetProcAddress(hDll,"??Bid@locale@std@@QAEIXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2B4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2B8) = ::GetProcAddress(hDll,"?pbase@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IBEPADXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2B8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2BC) = ::GetProcAddress(hDll,"?setp@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEXPAD0@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2BC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2C0) = ::GetProcAddress(hDll,"?setp@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IAEXPAD00@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2C0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2C4) = ::GetProcAddress(hDll,"??0?$basic_iostream@DU?$char_traits@D@std@@@std@@QAE@PAV?$basic_streambuf@DU?$char_traits@D@std@@@1@@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2C4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2C8) = ::GetProcAddress(hDll,"?_Lock@?$basic_streambuf@DU?$char_traits@D@std@@@std@@UAEXXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2C8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2CC) = ::GetProcAddress(hDll,"?_Unlock@?$basic_streambuf@DU?$char_traits@D@std@@@std@@UAEXXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2CC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2D0) = ::GetProcAddress(hDll,"?uflow@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MAEHXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2D0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2D4) = ::GetProcAddress(hDll,"?setbuf@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MAEPAV12@PAD_J@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2D4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2D8) = ::GetProcAddress(hDll,"?sync@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MAEHXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2D8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2DC) = ::GetProcAddress(hDll,"?imbue@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MAEXABVlocale@2@@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2DC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2E0) = ::GetProcAddress(hDll,"??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2E0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2E4) = ::GetProcAddress(hDll,"??1?$basic_iostream@DU?$char_traits@D@std@@@std@@UAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2E4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2E8) = ::GetProcAddress(hDll,"_Mtx_destroy_in_situ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2E8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2EC) = ::GetProcAddress(hDll,"_Mtx_init_in_situ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2EC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2F0) = ::GetProcAddress(hDll,"?_Xbad_function_call@std@@YAXXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2F0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2F4) = ::GetProcAddress(hDll,"?setw@std@@YA?AU?$_Smanip@_J@1@_J@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2F4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2F8) = ::GetProcAddress(hDll,"?id@?$ctype@D@std@@2V0locale@2@A");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2F8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B2FC) = ::GetProcAddress(hDll,"?fill@?$basic_ios@DU?$char_traits@D@std@@@std@@QAEDD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B2FC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B300) = ::GetProcAddress(hDll,"?snextc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B300))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B304) = ::GetProcAddress(hDll,"??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAVios_base@1@AAV21@@Z@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B304))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B308) = ::GetProcAddress(hDll,"?_Ipfx@?$basic_istream@DU?$char_traits@D@std@@@std@@QAE_N_N@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B308))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B30C) = ::GetProcAddress(hDll,"?read@?$basic_istream@DU?$char_traits@D@std@@@std@@QAEAAV12@PAD_J@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B30C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B310) = ::GetProcAddress(hDll,"?gcount@?$basic_istream@DU?$char_traits@D@std@@@std@@QBE_JXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B310))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B314) = ::GetProcAddress(hDll,"?seekg@?$basic_istream@DU?$char_traits@D@std@@@std@@QAEAAV12@V?$fpos@U_Mbstatet@@@2@@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B314))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B318) = ::GetProcAddress(hDll,"?tellg@?$basic_istream@DU?$char_traits@D@std@@@std@@QAE?AV?$fpos@U_Mbstatet@@@2@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B318))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B31C) = ::GetProcAddress(hDll,"?getloc@ios_base@std@@QBE?AVlocale@2@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B31C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B320) = ::GetProcAddress(hDll,"?setf@ios_base@std@@QAEHHH@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B320))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B324) = ::GetProcAddress(hDll,"?setf@ios_base@std@@QAEHH@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B324))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B328) = ::GetProcAddress(hDll,"?fail@ios_base@std@@QBE_NXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B328))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B32C) = ::GetProcAddress(hDll,"?rdstate@ios_base@std@@QBEHXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B32C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B330) = ::GetProcAddress(hDll,"?_Getcat@?$ctype@D@std@@SAIPAPBVfacet@locale@2@PBV42@@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B330))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B334) = ::GetProcAddress(hDll,"?is@?$ctype@D@std@@QBE_NFD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B334))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B338) = ::GetProcAddress(hDll,"?_Throw_C_error@std@@YAXH@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B338))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B33C) = ::GetProcAddress(hDll,"_Mtx_lock");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B33C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B340) = ::GetProcAddress(hDll,"_Mtx_unlock");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B340))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B344) = ::GetProcAddress(hDll,"?_Init@locale@std@@CAPAV_Locimp@12@_N@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B344))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B348) = ::GetProcAddress(hDll,"?_Decref@facet@locale@std@@UAEPAV_Facet_base@3@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B348))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B34C) = ::GetProcAddress(hDll,"?_Incref@facet@locale@std@@UAEXXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B34C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B350) = ::GetProcAddress(hDll,"_Strxfrm");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B350))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B354) = ::GetProcAddress(hDll,"?_Xregex_error@std@@YAXW4error_type@regex_constants@1@@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B354))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B358) = ::GetProcAddress(hDll,"?id@?$collate@D@std@@2V0locale@2@A");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B358))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B35C) = ::GetProcAddress(hDll,"_Strcoll");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B35C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B360) = ::GetProcAddress(hDll,"_Xtime_get_ticks");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B360))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B364) = ::GetProcAddress(hDll,"?c_str@?$_Yarn@D@std@@QBEPBDXZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B364))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B368) = ::GetProcAddress(hDll,"?tolower@?$ctype@D@std@@QBEPBDPADPBD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B368))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B36C) = ::GetProcAddress(hDll,"?tolower@?$ctype@D@std@@QBEDD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B36C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B370) = ::GetProcAddress(hDll,"??1facet@locale@std@@MAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B370))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B374) = ::GetProcAddress(hDll,"??0facet@locale@std@@IAE@I@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B374))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B378) = ::GetProcAddress(hDll,"?_Getcoll@_Locinfo@std@@QBE?AU_Collvec@@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B378))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B37C) = ::GetProcAddress(hDll,"??1_Locinfo@std@@QAE@XZ");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B37C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B380) = ::GetProcAddress(hDll,"??0_Locinfo@std@@QAE@PBD@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B380))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B384) = ::GetProcAddress(hDll,"_Mtx_trylock");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B384))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B388) = ::GetProcAddress(hDll,"?_Winerror_map@std@@YAHH@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B388))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B38C) = ::GetProcAddress(hDll,"?_Syserror_map@std@@YAPBDH@Z");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B38C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B390) = ::GetProcAddress(hDll,"_Query_perf_frequency");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B390))
		return FALSE;

	hDll = ::LoadLibraryA("d3dx9_43.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"d3dx9_43.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B79C) = ::GetProcAddress(hDll,"D3DXCreateTextureFromFileInMemory");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B79C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B7A0) = ::GetProcAddress(hDll,"D3DXGetImageInfoFromFileA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B7A0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B7A4) = ::GetProcAddress(hDll,"D3DXCreateTextureFromFileExA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B7A4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B7A8) = ::GetProcAddress(hDll,"D3DXCreateTextureFromFileInMemoryEx");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B7A8))
		return FALSE;

	hDll = ::LoadLibraryA("WINMM.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"WINMM.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B458) = ::GetProcAddress(hDll,"PlaySoundA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B458))
		return FALSE;

	hDll = ::LoadLibraryA("IMM32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"IMM32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B074) = ::GetProcAddress(hDll,"ImmSetCompositionWindow");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B074))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B078) = ::GetProcAddress(hDll,"ImmGetContext");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B078))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B07C) = ::GetProcAddress(hDll,"ImmReleaseContext");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B07C))
		return FALSE;

	hDll = ::LoadLibraryA("XINPUT1_4.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"XINPUT1_4.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B538) = ::GetProcAddress(hDll,(LPCSTR)0x4);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B538))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B53C) = ::GetProcAddress(hDll,(LPCSTR)0x2);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B53C))
		return FALSE;

	hDll = ::LoadLibraryA("WININET.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"WININET.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B450) = ::GetProcAddress(hDll,"InternetCheckConnectionA");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B450))
		return FALSE;

	hDll = ::LoadLibraryA("VCRUNTIME140.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"VCRUNTIME140.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B400) = ::GetProcAddress(hDll,"_setjmp3");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B400))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B404) = ::GetProcAddress(hDll,"__current_exception");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B404))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B408) = ::GetProcAddress(hDll,"__current_exception_context");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B408))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B40C) = ::GetProcAddress(hDll,"_CxxThrowException");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B40C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B410) = ::GetProcAddress(hDll,"__CxxFrameHandler3");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B410))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B414) = ::GetProcAddress(hDll,"__std_type_info_destroy_list");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B414))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B418) = ::GetProcAddress(hDll,"__std_exception_destroy");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B418))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B41C) = ::GetProcAddress(hDll,"__std_exception_copy");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B41C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B420) = ::GetProcAddress(hDll,"longjmp");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B420))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B424) = ::GetProcAddress(hDll,"memcmp");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B424))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B428) = ::GetProcAddress(hDll,"memchr");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B428))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B42C) = ::GetProcAddress(hDll,"memmove");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B42C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B430) = ::GetProcAddress(hDll,"strrchr");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B430))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B434) = ::GetProcAddress(hDll,"memcpy");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B434))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B438) = ::GetProcAddress(hDll,"_purecall");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B438))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B43C) = ::GetProcAddress(hDll,"strstr");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B43C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B440) = ::GetProcAddress(hDll,"memset");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B440))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B444) = ::GetProcAddress(hDll,"strchr");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B444))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B448) = ::GetProcAddress(hDll,"_except_handler4_common");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B448))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-heap-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-heap-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B594) = ::GetProcAddress(hDll,"_callnewh");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B594))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B598) = ::GetProcAddress(hDll,"malloc");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B598))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B59C) = ::GetProcAddress(hDll,"realloc");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B59C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5A0) = ::GetProcAddress(hDll,"free");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5A0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5A4) = ::GetProcAddress(hDll,"calloc");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5A4))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-runtime-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-runtime-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B618) = ::GetProcAddress(hDll,"_register_onexit_function");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B618))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B61C) = ::GetProcAddress(hDll,"_execute_onexit_table");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B61C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B620) = ::GetProcAddress(hDll,"_crt_atexit");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B620))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B624) = ::GetProcAddress(hDll,"_cexit");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B624))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B628) = ::GetProcAddress(hDll,"_initterm");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B628))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B62C) = ::GetProcAddress(hDll,"_initterm_e");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B62C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B630) = ::GetProcAddress(hDll,"_initialize_narrow_environment");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B630))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B634) = ::GetProcAddress(hDll,"__sys_nerr");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B634))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B638) = ::GetProcAddress(hDll,"_configure_narrow_argv");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B638))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B63C) = ::GetProcAddress(hDll,"_beginthreadex");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B63C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B640) = ::GetProcAddress(hDll,"_getpid");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B640))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B644) = ::GetProcAddress(hDll,"strerror");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B644))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B648) = ::GetProcAddress(hDll,"_seh_filter_dll");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B648))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B64C) = ::GetProcAddress(hDll,"abort");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B64C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B650) = ::GetProcAddress(hDll,"_initialize_onexit_table");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B650))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B654) = ::GetProcAddress(hDll,"_errno");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B654))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B658) = ::GetProcAddress(hDll,"exit");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B658))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B65C) = ::GetProcAddress(hDll,"terminate");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B65C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B660) = ::GetProcAddress(hDll,"_invalid_parameter_noinfo_noreturn");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B660))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B664) = ::GetProcAddress(hDll,"system");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B664))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B668) = ::GetProcAddress(hDll,"__sys_errlist");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B668))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-math-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-math-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B5BC) = ::GetProcAddress(hDll,"_libm_sse2_pow_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5BC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5C0) = ::GetProcAddress(hDll,"floor");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5C0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5C4) = ::GetProcAddress(hDll,"frexp");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5C4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5C8) = ::GetProcAddress(hDll,"_CIfmod");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5C8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5CC) = ::GetProcAddress(hDll,"_fdclass");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5CC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5D0) = ::GetProcAddress(hDll,"ldexp");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5D0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5D4) = ::GetProcAddress(hDll,"_CIatan2");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5D4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5D8) = ::GetProcAddress(hDll,"_dsign");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5D8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5DC) = ::GetProcAddress(hDll,"_libm_sse2_asin_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5DC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5E0) = ::GetProcAddress(hDll,"_libm_sse2_cos_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5E0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5E4) = ::GetProcAddress(hDll,"_libm_sse2_exp_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5E4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5E8) = ::GetProcAddress(hDll,"_libm_sse2_log10_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5E8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5EC) = ::GetProcAddress(hDll,"_libm_sse2_log_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5EC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5F0) = ::GetProcAddress(hDll,"_libm_sse2_sin_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5F0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5F4) = ::GetProcAddress(hDll,"_libm_sse2_sqrt_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5F4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5F8) = ::GetProcAddress(hDll,"_libm_sse2_tan_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5F8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5FC) = ::GetProcAddress(hDll,"ceil");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5FC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B600) = ::GetProcAddress(hDll,"_libm_sse2_acos_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B600))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B604) = ::GetProcAddress(hDll,"_libm_sse2_atan_precise");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B604))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B608) = ::GetProcAddress(hDll,"fmaxf");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B608))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B60C) = ::GetProcAddress(hDll,"copysignf");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B60C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B610) = ::GetProcAddress(hDll,"_dclass");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B610))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-stdio-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-stdio-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B670) = ::GetProcAddress(hDll,"ungetc");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B670))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B674) = ::GetProcAddress(hDll,"fsetpos");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B674))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B678) = ::GetProcAddress(hDll,"fread");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B678))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B67C) = ::GetProcAddress(hDll,"tmpnam");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B67C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B680) = ::GetProcAddress(hDll,"_fseeki64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B680))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B684) = ::GetProcAddress(hDll,"_get_stream_buffer_pointers");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B684))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B688) = ::GetProcAddress(hDll,"fgetpos");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B688))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B68C) = ::GetProcAddress(hDll,"fputc");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B68C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B690) = ::GetProcAddress(hDll,"tmpfile");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B690))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B694) = ::GetProcAddress(hDll,"_popen");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B694))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B698) = ::GetProcAddress(hDll,"_pclose");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B698))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B69C) = ::GetProcAddress(hDll,"_ftelli64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B69C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6A0) = ::GetProcAddress(hDll,"clearerr");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6A0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6A4) = ::GetProcAddress(hDll,"fclose");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6A4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6A8) = ::GetProcAddress(hDll,"fflush");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6A8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6AC) = ::GetProcAddress(hDll,"fwrite");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6AC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6B0) = ::GetProcAddress(hDll,"__stdio_common_vsprintf");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6B0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6B4) = ::GetProcAddress(hDll,"_close");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6B4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6B8) = ::GetProcAddress(hDll,"__stdio_common_vfprintf");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6B8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6BC) = ::GetProcAddress(hDll,"getc");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6BC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6C0) = ::GetProcAddress(hDll,"ferror");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6C0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6C4) = ::GetProcAddress(hDll,"ftell");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6C4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6C8) = ::GetProcAddress(hDll,"__acrt_iob_func");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6C8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6CC) = ::GetProcAddress(hDll,"fseek");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6CC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6D0) = ::GetProcAddress(hDll,"_wfopen");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6D0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6D4) = ::GetProcAddress(hDll,"__stdio_common_vsscanf");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6D4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6D8) = ::GetProcAddress(hDll,"__stdio_common_vsprintf_s");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6D8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6DC) = ::GetProcAddress(hDll,"freopen");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6DC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6E0) = ::GetProcAddress(hDll,"_write");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6E0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6E4) = ::GetProcAddress(hDll,"_lseeki64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6E4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6E8) = ::GetProcAddress(hDll,"_read");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6E8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6EC) = ::GetProcAddress(hDll,"fopen");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6EC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6F0) = ::GetProcAddress(hDll,"fgets");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6F0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6F4) = ::GetProcAddress(hDll,"_open");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6F4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6F8) = ::GetProcAddress(hDll,"fgetc");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6F8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B6FC) = ::GetProcAddress(hDll,"setvbuf");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B6FC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B700) = ::GetProcAddress(hDll,"feof");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B700))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B704) = ::GetProcAddress(hDll,"fputs");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B704))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-string-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-string-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B70C) = ::GetProcAddress(hDll,"strpbrk");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B70C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B710) = ::GetProcAddress(hDll,"strncmp");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B710))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B714) = ::GetProcAddress(hDll,"tolower");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B714))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B718) = ::GetProcAddress(hDll,"_strdup");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B718))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B71C) = ::GetProcAddress(hDll,"strcspn");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B71C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B720) = ::GetProcAddress(hDll,"strcpy_s");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B720))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B724) = ::GetProcAddress(hDll,"isupper");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B724))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B728) = ::GetProcAddress(hDll,"strncpy");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B728))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B72C) = ::GetProcAddress(hDll,"towlower");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B72C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B730) = ::GetProcAddress(hDll,"isspace");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B730))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B734) = ::GetProcAddress(hDll,"isblank");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B734))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B738) = ::GetProcAddress(hDll,"isalnum");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B738))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B73C) = ::GetProcAddress(hDll,"toupper");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B73C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B740) = ::GetProcAddress(hDll,"iswalpha");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B740))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B744) = ::GetProcAddress(hDll,"isdigit");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B744))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B748) = ::GetProcAddress(hDll,"strcoll");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B748))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B74C) = ::GetProcAddress(hDll,"iscntrl");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B74C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B750) = ::GetProcAddress(hDll,"isxdigit");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B750))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B754) = ::GetProcAddress(hDll,"isgraph");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B754))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B758) = ::GetProcAddress(hDll,"ispunct");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B758))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B75C) = ::GetProcAddress(hDll,"isalpha");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B75C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B760) = ::GetProcAddress(hDll,"islower");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B760))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B764) = ::GetProcAddress(hDll,"strspn");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B764))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-filesystem-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-filesystem-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B570) = ::GetProcAddress(hDll,"remove");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B570))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B574) = ::GetProcAddress(hDll,"rename");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B574))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B578) = ::GetProcAddress(hDll,"_access");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B578))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B57C) = ::GetProcAddress(hDll,"_stat64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B57C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B580) = ::GetProcAddress(hDll,"_fstat64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B580))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B584) = ::GetProcAddress(hDll,"_lock_file");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B584))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B588) = ::GetProcAddress(hDll,"_unlock_file");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B588))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B58C) = ::GetProcAddress(hDll,"_unlink");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B58C))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-utility-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-utility-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B78C) = ::GetProcAddress(hDll,"qsort");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B78C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B790) = ::GetProcAddress(hDll,"srand");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B790))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B794) = ::GetProcAddress(hDll,"rand");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B794))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-convert-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-convert-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B544) = ::GetProcAddress(hDll,"strtoul");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B544))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B548) = ::GetProcAddress(hDll,"strtol");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B548))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B54C) = ::GetProcAddress(hDll,"atoi");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B54C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B550) = ::GetProcAddress(hDll,"atof");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B550))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B554) = ::GetProcAddress(hDll,"strtod");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B554))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B558) = ::GetProcAddress(hDll,"strtoll");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B558))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B55C) = ::GetProcAddress(hDll,"strtoull");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B55C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B560) = ::GetProcAddress(hDll,"wcstombs");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B560))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-locale-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-locale-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B5AC) = ::GetProcAddress(hDll,"setlocale");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5AC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5B0) = ::GetProcAddress(hDll,"localeconv");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5B0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B5B4) = ::GetProcAddress(hDll,"___lc_codepage_func");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B5B4))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-time-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-time-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B76C) = ::GetProcAddress(hDll,"clock");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B76C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B770) = ::GetProcAddress(hDll,"_difftime64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B770))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B774) = ::GetProcAddress(hDll,"_time64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B774))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B778) = ::GetProcAddress(hDll,"_localtime64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B778))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B77C) = ::GetProcAddress(hDll,"strftime");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B77C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B780) = ::GetProcAddress(hDll,"_gmtime64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B780))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B784) = ::GetProcAddress(hDll,"_mktime64");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B784))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-environment-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-environment-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B568) = ::GetProcAddress(hDll,"getenv");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B568))
		return FALSE;

	hDll = ::LoadLibraryA("WS2_32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"WS2_32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Rawetrip_VA(0x1027B4AC) = ::GetProcAddress(hDll,(LPCSTR)0x17);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4AC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4B0) = ::GetProcAddress(hDll,(LPCSTR)0x13);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4B0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4B4) = ::GetProcAddress(hDll,(LPCSTR)0x70);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4B4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4B8) = ::GetProcAddress(hDll,"WSAIoctl");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4B8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4BC) = ::GetProcAddress(hDll,"WSACloseEvent");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4BC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4C0) = ::GetProcAddress(hDll,(LPCSTR)0x73);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4C0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4C4) = ::GetProcAddress(hDll,"WSACreateEvent");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4C4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4C8) = ::GetProcAddress(hDll,(LPCSTR)0x74);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4C8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4CC) = ::GetProcAddress(hDll,"WSAEnumNetworkEvents");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4CC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4D0) = ::GetProcAddress(hDll,"WSAEventSelect");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4D0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4D4) = ::GetProcAddress(hDll,"WSAResetEvent");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4D4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4D8) = ::GetProcAddress(hDll,(LPCSTR)0x97);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4D8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4DC) = ::GetProcAddress(hDll,"WSAWaitForMultipleEvents");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4DC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4E0) = ::GetProcAddress(hDll,(LPCSTR)0x3);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4E0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4E4) = ::GetProcAddress(hDll,(LPCSTR)0x6F);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4E4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4E8) = ::GetProcAddress(hDll,(LPCSTR)0x10);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4E8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4EC) = ::GetProcAddress(hDll,(LPCSTR)0x12);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4EC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4F0) = ::GetProcAddress(hDll,(LPCSTR)0x2);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4F0))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4F4) = ::GetProcAddress(hDll,(LPCSTR)0x1);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4F4))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4F8) = ::GetProcAddress(hDll,(LPCSTR)0x8);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4F8))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B4FC) = ::GetProcAddress(hDll,(LPCSTR)0xF);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B4FC))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B500) = ::GetProcAddress(hDll,(LPCSTR)0xD);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B500))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B504) = ::GetProcAddress(hDll,"getaddrinfo");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B504))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B508) = ::GetProcAddress(hDll,(LPCSTR)0x4);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B508))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B50C) = ::GetProcAddress(hDll,(LPCSTR)0x5);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B50C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B510) = ::GetProcAddress(hDll,(LPCSTR)0x6);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B510))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B514) = ::GetProcAddress(hDll,"freeaddrinfo");
	if(!*(FARPROC*)Rawetrip_VA(0x1027B514))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B518) = ::GetProcAddress(hDll,(LPCSTR)0x39);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B518))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B51C) = ::GetProcAddress(hDll,(LPCSTR)0xA);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B51C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B520) = ::GetProcAddress(hDll,(LPCSTR)0x11);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B520))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B524) = ::GetProcAddress(hDll,(LPCSTR)0x7);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B524))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B528) = ::GetProcAddress(hDll,(LPCSTR)0x14);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B528))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B52C) = ::GetProcAddress(hDll,(LPCSTR)0x9);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B52C))
		return FALSE;
	*(FARPROC*)Rawetrip_VA(0x1027B530) = ::GetProcAddress(hDll,(LPCSTR)0x15);
	if(!*(FARPROC*)Rawetrip_VA(0x1027B530))
		return FALSE;

	VirtualProtect(&Rawetrip_InitData, sizeof(Rawetrip_InitData), PAGE_EXECUTE_READWRITE, &oldProtect);

	*(FARPROC*)&fInitData = (FARPROC)&Rawetrip_InitData[0];
	fInitData(g_hRawetrip,Rawetrip_RVA,NULL);

	*(FARPROC*)&Rawetrip_DllEntryPoint = (FARPROC)Rawetrip_VA(0x1026D404);
	return TRUE;
}


