/*******************************************************************************
	Generated by: DLL to C version 3.91
	Date: 2022-11-6
	Description: The declaration of functions and variables for rawetrip.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#if !defined(_RAWETRIP_SUPP_H_00769000_INCLUDED_)
#define _RAWETRIP_SUPP_H_00769000_INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


#include <windows.h>

#pragma pack(push)
#pragma pack(1)

#include "Rawetrip_rdata.h"
#include "Rawetrip_data.h"

__declspec(align(16)) struct stRawetrip
{
	UCHAR Header[0x1000];
	UCHAR Text[0x27A000];
	stRawetrip_rdata Rdata;
	stRawetrip_data Data;
	UCHAR Rsrc[0x1000];
	UCHAR Reloc[0x1D000];
};

#pragma pack(pop)

__declspec(align(16)) extern stRawetrip Rawetrip;

/* Data for initialization. */
extern UCHAR Rawetrip_InitData[0x26E96];

extern HMODULE g_hRawetrip;

/*
	Description: Access any address in the DLL.
	Parameters:
		rvaAddr: The RVA address you want to access.
*/
void* __stdcall Rawetrip_RVA(DWORD rvaAddr);

#define Rawetrip_VA(vaAddr) Rawetrip_RVA((vaAddr) - 0x10000000)


#endif // !defined(_RAWETRIP_SUPP_H_00769000_INCLUDED_)